(function() {var implementors = {};
implementors['libc'] = [];implementors['libr'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/ext/callbacks/struct.Struct__ToplevelCallback.html' title='libr::ext::callbacks::Struct__ToplevelCallback'>Struct__ToplevelCallback</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/ext/callbacks/struct.Struct__R_ObjectTable.html' title='libr::ext::callbacks::Struct__R_ObjectTable'>Struct__R_ObjectTable</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/ext/complex/struct.Rcomplex.html' title='libr::ext::complex::Rcomplex'>Rcomplex</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/ext/connections/struct.Struct_Rconn.html' title='libr::ext::connections::Struct_Rconn'>Struct_Rconn</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/ext/r_startup/struct.structRstart.html' title='libr::ext::r_startup::structRstart'>structRstart</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/ext/rdynload/struct.R_CMethodDef.html' title='libr::ext::rdynload::R_CMethodDef'>R_CMethodDef</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/ext/rdynload/struct.R_CallMethodDef.html' title='libr::ext::rdynload::R_CallMethodDef'>R_CallMethodDef</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/internals/struct.R_long_vec_hdr_t.html' title='libr::internals::R_long_vec_hdr_t'>R_long_vec_hdr_t</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/internals/struct.Struct_R_outpstream_st.html' title='libr::internals::Struct_R_outpstream_st'>Struct_R_outpstream_st</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libr/internals/struct.Struct_R_inpstream_st.html' title='libr::internals::Struct_R_inpstream_st'>Struct_R_inpstream_st</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
