// automatically generated by rust-bindgen

#[repr(C)]
#[derive(Copy)]
pub struct Rcomplex {
    pub r: ::libc::c_double,
    pub i: ::libc::c_double,
}
impl ::std::clone::Clone for Rcomplex {
    fn clone(&self) -> Self {
        *self
    }
}
impl ::std::default::Default for Rcomplex {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
