// automatically generated by rust-bindgen

#[link(name = "R")]
extern {
    pub fn Rf_error(arg1: *const ::libc::c_char, ...) -> ();
    pub fn UNIMPLEMENTED(arg1: *const ::libc::c_char) -> ();
    pub fn WrongArgCount(arg1: *const ::libc::c_char) -> ();
    pub fn Rf_warning(arg1: *const ::libc::c_char, ...) -> ();
    pub fn R_ShowMessage(s: *const ::libc::c_char) -> ();
}
