// automatically generated by rust-bindgen

use super::super::va_list::va_list;

extern "C" {
    pub fn Rprintf(arg1: *const ::libc::c_char, ...) -> ();
    pub fn REprintf(arg1: *const ::libc::c_char, ...) -> ();
    pub fn Rvprintf(arg1: *const ::libc::c_char, arg2: va_list) -> ();
    pub fn REvprintf(arg1: *const ::libc::c_char, arg2: va_list) -> ();
}
