/* automatically generated by rust-bindgen */
const HAVE_F77_UNDERSCORE = 1;
const IEEE_754 = 1;
const HAVE_VISIBILITY_ATTRIBUTE = 1;
const SUPPORT_UTF8 = 1;
const SUPPORT_MBCS = 1;
const ENABLE_NLS   = 1;
const SUPPORT_OPENMP = 1;
const SIZEOF_SIZE_T = 8;
const HAVE_ALLOCA_H = 1;

