// automatically generated by rust-bindgen
#[allow(dead_code)]
const HAVE_F77_UNDERSCORE: u8 = 1;
#[allow(dead_code)]
const IEEE_754: u8 = 1;
#[allow(dead_code)]
const HAVE_VISIBILITY_ATTRIBUTE: u8 = 1;
#[allow(dead_code)]
const SUPPORT_UTF8: u8 = 1;
#[allow(dead_code)]
const SUPPORT_MBCS: u8 = 1;
#[allow(dead_code)]
const ENABLE_NLS: u8 = 1;
#[allow(dead_code)]
const SUPPORT_OPENMP: u8 = 1;
#[allow(dead_code)]
const SIZEOF_SIZE_T: u8 = 8;
#[allow(dead_code)]
const HAVE_ALLOCA_H: u8 = 1;
