/* automatically generated by rust-bindgen */

pub const R_VERSION: u32 = 197635;
pub const R_NICK: &'static [u8; 17usize] = b"Kite-Eating Tree\0";
pub const R_MAJOR: &'static [u8; 2usize] = b"3\0";
pub const R_MINOR: &'static [u8; 4usize] = b"4.3\0";
pub const R_STATUS: &'static [u8; 1usize] = b"\0";
pub const R_YEAR: &'static [u8; 5usize] = b"2017\0";
pub const R_MONTH: &'static [u8; 3usize] = b"11\0";
pub const R_DAY: &'static [u8; 3usize] = b"30\0";
pub const R_SVN_REVISION: u32 = 73796;
