(function() {var implementors = {};
implementors['libc'] = [];implementors['libr'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='libr/ext/parse/enum.ParseStatus.html' title='libr::ext::parse::ParseStatus'>ParseStatus</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='libr/ext/r_startup/enum.SA_TYPE.html' title='libr::ext::r_startup::SA_TYPE'>SA_TYPE</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='libr/ext/rdynload/enum.R_NativeArgStyle.html' title='libr::ext::rdynload::R_NativeArgStyle'>R_NativeArgStyle</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='libr/ext/rdynload/enum.NativeSymbolType.html' title='libr::ext::rdynload::NativeSymbolType'>NativeSymbolType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='libr/internals/struct.R_long_vec_hdr_t.html' title='libr::internals::R_long_vec_hdr_t'>R_long_vec_hdr_t</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='libr/internals/enum.cetype_t.html' title='libr::internals::cetype_t'>cetype_t</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='libr/internals/enum.R_pstream_format_t.html' title='libr::internals::R_pstream_format_t'>R_pstream_format_t</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
